name: '✅ Check everything:'

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check for package.json
        id: check_package
        run: |
          if [ -f "package.json" ]; then
            echo "package.json found."
            echo "run_tests=true" >> $GITHUB_ENV
          else
            echo "No package.json found, skipping build and tests."
            echo "run_tests=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        if: ${{ env.run_tests == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        if: ${{ env.run_tests == 'true' }}
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npm install

      - name: Run Tests
        if: ${{ env.run_tests == 'true' }}
        run: |
          if [ -f "jest.config.js" ]; then
            echo "Running tests..."
            npm test
          else
            echo "No Jest configuration found, skipping tests."
          fi

      - name: Build Packages
        if: ${{ env.run_tests == 'true' }}
        run: npx lerna run build
