name: '📦 Publish packages'

on:
  workflow_call:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npm install

      - name: Check PR Labels
        id: check_labels
        run: |
          LABELS=$(jq -r '.pull_request.labels | .[] | .name' "$GITHUB_EVENT_PATH")
          echo "Labels found: $LABELS"
          if [[ "$LABELS" == *"stable"* ]]; then
            echo "Publishing as stable."
            echo "publish_type=stable" >> $GITHUB_ENV
          elif [[ "$LABELS" == *"beta"* ]]; then
            echo "Publishing as beta."
            echo "publish_type=beta" >> $GITHUB_ENV
          else
            echo "Publishing as alpha."
            echo "publish_type=alpha" >> $GITHUB_ENV
          fi

      - name: Install dependencies with Lerna
        run: npx lerna run install

      - name: Publish with Lerna
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          set -e 
          if [ "$publish_type" == "stable" ]; then
            npx lerna publish patch --yes --conventional-commits --message "chore: update version and changelog" --conventional-graduate || true
          elif [ "$publish_type" == "beta" ]; then
            npx lerna publish prerelease --preid beta --yes --conventional-commits --message "chore: update version and changelog" --conventional-prerelease || true
          else
            npx lerna publish prerelease --preid alpha --yes --conventional-commits --message "chore: update version and changelog" --conventional-prerelease || true
          fi

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add packages/*/CHANGELOG.md packages/*/package.json
          git commit -m "chore: update changelogs and package versions" || echo "No changes to commit"
